name: Rotation Serveur Minecraft

on:
  schedule:
    # Lance le script à 00:00, 08:00 et 16:00 UTC
    - cron: "0 0,8,16 * * *"
  workflow_dispatch: # Permet de lancer manuellement pour tester

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 1. On installe LFTP normalement
      - name: Installation de LFTP
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp

      # 2. On installe Firefox via l'action officielle
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: "latest"

      # 3. On installe Geckodriver (CORRECTION ICI : use @latest)
      - name: Setup Geckodriver
        uses: browser-actions/setup-geckodriver@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Installation des librairies Python
        run: |
          pip install -r requirements.txt

      - name: Exécution du Worker
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          IP_NEW_SERVER: "orny"
        run: python worker.py
