name: Rotation Serveur Minecraft

on:
  schedule:
    - cron: "0 7,15,23 * * *"
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          pip install requests beautifulsoup4

      - name: Run Worker HTTP
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          IP_NEW_SERVER: "orny"
        run: python worker.py
